In [1]:
#!pip install --upgrade tensorflow

In [2]:
import tensorflow as tf
tf.version.VERSION   or print(tf.__version__)


'2.3.0'

In [3]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# building a computational graph
a=tf.constant(2)
b=tf.constant(4)
c=a+b


print(c)


Tensor("add:0", shape=(), dtype=int32)


In [4]:
#running a computational graph
ssn = tf.compat.v1.Session()   # tf.compat.v1 module contains the complete TensorFlow 1.x API, with its original semantics.

ssn.run(c)

6

In [5]:
x1=tf.constant([1,2,4,5])
x2=tf.constant([2,3,4,5])

#result = tf.multiply(x1,x2)
result=x1*x2

print(result)


Tensor("mul:0", shape=(4,), dtype=int32)


In [6]:

ssn.run(result)

array([ 2,  6, 16, 25])


# Placeholder  : not providing values at the time of declaration but providing values later at the time of execution

In [7]:
#a=tf.placeholder(tf.float32)
a= tf.compat.v1.placeholder(tf.float32)
#b=tf.placeholder(tf.float32)
b= tf.compat.v1.placeholder(tf.float32)
c=a+b
c

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [8]:

ssn.run(c,{a:1,b:4})  # assigning values to a abd b here

5.0

# Placeholder is very useful when we want to give different input values

In [9]:
ssn.run(c,{a:[1,2,3],b:[4,2,1]})  # assigning values to a abd b here

array([5., 4., 4.], dtype=float32)

In [10]:
ssn.run(c,{a:[1,2],b:[4,2]})

array([5., 4.], dtype=float32)

In [11]:
ssn.run(c,{a:1,b:2})

3.0


# Variable

In [12]:
#x=tf.Variable([1])
x=tf.compat.v1.Variable([1])

#q=tf.Variable([.1],tf.float32)

#w=tf.Variable([3])
w=tf.compat.v1.Variable([3])
c=x*w
init = tf.compat.v1.global_variables_initializer()

ssn.run(init)
ssn.run(c)


array([3])

# To do:
## Task: Install Tensorflow on your device and try the code which I have explained today.